# Generated by Django 4.2.1 on 2025-02-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mes_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.class')),
            ],
        ),
    ]
