# Generated by Django 4.2.1 on 2024-12-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0020_task_answer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskcollectiontasks', to='tasks.task')),
                ('task_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskcollections.taskcollection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('task_collection', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskCollectionSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField()),
                ('score', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('task_collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskcollections.taskcollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskcollection',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='collections', through='taskcollections.TaskCollectionTask', to='tasks.task'),
        ),
    ]
