# Generated by Django 4.2.1 on 2024-11-23 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('taskcollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollectionsolve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcollection',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.task'),
        ),
    ]
