# Generated by Django 4.2.1 on 2025-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0002_taskcollection_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
