# Generated by Django 4.2.1 on 2025-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0003_alter_taskcollection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
