# Generated by Django 5.1.6 on 2025-03-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0005_alter_taskcollectionsolve_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollectiontask',
            name='task_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskcollectiontasks', to='taskcollections.taskcollection'),
        ),
    ]
