# Generated by Django 5.1.6 on 2025-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0006_alter_taskcollectiontask_task_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollectionsolve',
            name='test_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
