# Generated by Django 5.1.6 on 2025-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0009_remove_taskcollectionsolve_is_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
