# Generated by Django 5.1.6 on 2025-03-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0010_alter_taskcollection_is_exam'),
        ('tasks', '0034_tasksubject_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollection',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasksubject'),
            preserve_default=False,
        ),
    ]
