# Generated by Django 5.1.6 on 2025-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0011_taskcollection_subject'),
        ('users', '0005_achievement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollectionsolve',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='solves', to='users.achievement'),
        ),
    ]
