# Generated by Django 5.1.6 on 2025-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollections', '0012_taskcollectionsolve_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcollection',
            options={'verbose_name': 'Подборка задач', 'verbose_name_plural': 'Подборки задач'},
        ),
        migrations.AlterModelOptions(
            name='taskcollectionsolve',
            options={'verbose_name': 'Решение подборки задач', 'verbose_name_plural': 'Решения подборок задач'},
        ),
        migrations.AlterModelOptions(
            name='taskcollectiontask',
            options={'ordering': ['order'], 'verbose_name': 'Связь задач и подборок', 'verbose_name_plural': 'Связи задач и подборок'},
        ),
        migrations.AddField(
            model_name='taskcollectionsolve',
            name='max_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
