# Generated by Django 5.1.6 on 2025-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
