# Generated by Django 5.1.6 on 2025-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_achievement_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='tginvitation',
            options={'verbose_name': 'ТГ приглашение', 'verbose_name_plural': 'ТГ приглашения'},
        ),
    ]
