# Generated by Django 5.1.6 on 2025-05-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_achievement_options_alter_tginvitation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_town',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
