# Generated by Django 4.2.1 on 2025-01-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursemodule_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['-order']},
        ),
    ]
