# Generated by Django 4.2.1 on 2025-01-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursemodule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={},
        ),
    ]
