# Generated by Django 4.2.1 on 2025-01-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursemodule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursemodule', to='courses.module'),
        ),
    ]
