# Generated by Django 4.2.1 on 2025-01-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursemodule_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lessons',
        ),
    ]
