# Generated by Django 4.2.1 on 2025-01-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_module_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulelessons', to='courses.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='modules', through='courses.ModuleLesson', to='courses.lesson'),
        ),
    ]
