# Generated by Django 4.2.1 on 2025-01-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_modulelesson_module_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulelessons', to='courses.module'),
        ),
    ]
