# Generated by Django 4.2.1 on 2025-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_lesson_slug_remove_section_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='theory_section',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('task', 'task'), ('text', 'text')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='TheorySection',
        ),
    ]
