# Generated by Django 4.2.1 on 2025-01-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_description_section_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonsection',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lessonsection',
            old_name='position',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='lessonsection',
            unique_together={('lesson', 'section')},
        ),
    ]
