# Generated by Django 4.2.1 on 2025-01-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lessonsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsection',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessonsections', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessonsections', to='courses.section'),
        ),
    ]
