# Generated by Django 4.2.1 on 2025-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lessonsection_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsolve',
            name='answer',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
