# Generated by Django 4.2.1 on 2025-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_sectionsolve_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsolve',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionsolve',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
