# Generated by Django 4.2.1 on 2025-02-10 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='created_lessons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='created_modules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='created_sections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
