# Generated by Django 4.2.1 on 2025-02-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_lesson_created_by_module_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
