# Generated by Django 4.2.1 on 2025-02-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_lesson_description_remove_module_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
    ]
