# Generated by Django 4.2.1 on 2025-02-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
