# Generated by Django 5.1.6 on 2025-03-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_is_public'),
        ('tasks', '0035_tasknumberinexam_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasksubject'),
            preserve_default=False,
        ),
    ]
