# Generated by Django 5.1.6 on 2025-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_course_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order'], 'verbose_name': 'Связь курса и урока', 'verbose_name_plural': 'Связи курсов и уроков'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonsection',
            options={'ordering': ['order'], 'verbose_name': 'Связь уроков и секций', 'verbose_name_plural': 'Связи уроков и секций'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='modulelesson',
            options={'ordering': ['order'], 'verbose_name': 'Связь модуля и урока', 'verbose_name_plural': 'Связи модулей и уроков'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='sectionsolve',
            options={'verbose_name': 'Решение секции', 'verbose_name_plural': 'Решения секций'},
        ),
    ]
