# Generated by Django 5.1.6 on 2025-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_course_options_alter_coursemodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsolve',
            name='solve_status',
            field=models.CharField(choices=[('WA', 'WA'), ('OK', 'OK'), ('PA', 'PA')]),
        ),
    ]
