# Generated by Django 5.1.6 on 2025-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_sectionsolve_solve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsolve',
            name='solve_status',
            field=models.CharField(choices=[('WA', 'WA'), ('OK', 'OK'), ('PA', 'PA'), ('NA', 'NA')]),
        ),
    ]
