# Generated by Django 5.1.6 on 2025-05-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_sectionsolve_solve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users',
        ),
    ]
