# Generated by Django 4.2.1 on 2024-11-23 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolutions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.author'),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.difficultylevel'),
        ),
        migrations.AddField(
            model_name='task',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskexam'),
        ),
        migrations.AddField(
            model_name='task',
            name='number_in_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.tasknumberinexam'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.tasksource'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktopic'),
        ),
    ]
