# Generated by Django 4.2.1 on 2024-12-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_exam_remove_task_exam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexam',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskexam'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
