# Generated by Django 4.2.1 on 2024-12-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskexam_slug_alter_subject_exam_delete_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='TaskSubject',
        ),
    ]
