# Generated by Django 4.2.1 on 2024-12-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_subject_tasksubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknumberinexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='tasks.tasksubject'),
        ),
        migrations.AlterField(
            model_name='tasksubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='tasks.taskexam'),
        ),
        migrations.CreateModel(
            name='TaskBankAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BankAuthor', to='tasks.tasksubject')),
            ],
        ),
    ]
