# Generated by Django 4.2.1 on 2024-12-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasknumberinexam_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbankauthor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BankAuthors', to='tasks.tasksubject'),
        ),
    ]
