# Generated by Django 4.2.1 on 2024-12-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskbankauthor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubject',
            name='authors',
            field=models.ManyToManyField(related_name='subjects', to='tasks.author'),
        ),
        migrations.AlterField(
            model_name='taskbankauthor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='tasks.tasksubject'),
        ),
    ]
