# Generated by Django 4.2.1 on 2024-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tasksubject_authors_alter_taskbankauthor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubject',
            name='difficulty_levels',
            field=models.ManyToManyField(related_name='subjects', to='tasks.difficultylevel'),
        ),
    ]
