# Generated by Django 4.2.1 on 2024-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasknumberinexam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbankauthor',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskexam',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasksubject',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
