# Generated by Django 4.2.1 on 2024-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_tasknumberinexam_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbankauthor',
            name='tasks',
            field=models.ManyToManyField(related_name='bank_authors', to='tasks.task'),
        ),
    ]
