# Generated by Django 4.2.1 on 2024-12-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_taskbankauthor_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbankauthor',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='bank_authors',
            field=models.ManyToManyField(related_name='tasks', to='tasks.taskbankauthor'),
        ),
    ]
