# Generated by Django 4.2.1 on 2024-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_taskbankauthor_tasks_task_bank_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bank_authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='tasks.taskbankauthor'),
        ),
    ]
