# Generated by Django 4.2.1 on 2024-12-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_bank_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_available_in_bank',
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.author'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasksource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktopic'),
        ),
    ]
