# Generated by Django 4.2.1 on 2024-12-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_task_is_available_in_bank_alter_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.difficultylevel'),
        ),
    ]
