# Generated by Django 4.2.1 on 2024-12-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_task_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('table', 'table')], default='text'),
            preserve_default=False,
        ),
    ]
