# Generated by Django 4.2.1 on 2024-12-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0020_task_answer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_in_exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasknumberinexam'),
        ),
        migrations.AddField(
            model_name='task',
            name='actuality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.actuality'),
        ),
    ]
