# Generated by Django 4.2.1 on 2024-12-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_remove_task_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultylevel',
            name='exam',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskexam'),
            preserve_default=False,
        ),
    ]
