# Generated by Django 4.2.1 on 2024-12-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_remove_difficultylevel_exam_difficultylevel_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficultylevel',
            name='subject',
        ),
        migrations.AddField(
            model_name='difficultylevel',
            name='exam',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='dif_levels', to='tasks.taskexam'),
            preserve_default=False,
        ),
    ]
