# Generated by Django 4.2.1 on 2025-02-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_difficultylevel_subject_difficultylevel_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number_in_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasknumberinexam'),
        ),
    ]
