# Generated by Django 4.2.1 on 2025-02-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_task_number_in_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('table', 'table'), ('choice', 'choice')]),
        ),
    ]
