# Generated by Django 4.2.1 on 2025-02-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_task_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('table', 'table'), ('comparison', 'comparison'), ('sorting', 'sorting'), ('choice', 'choice')]),
        ),
    ]
