# Generated by Django 4.2.1 on 2025-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_task_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
