# Generated by Django 4.2.1 on 2025-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_rename_author_taskauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('table', 'table'), ('comparison', 'comparison'), ('sorting', 'sorting'), ('choice', 'choice'), ('open_answer', 'open_answer')]),
        ),
    ]
