# Generated by Django 5.1.6 on 2025-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_task_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubject',
            name='scale',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
