# Generated by Django 5.1.6 on 2025-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_tasksubject_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumberinexam',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
