# Generated by Django 5.1.6 on 2025-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_actuality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumberinexam',
            name='check_rule',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
