# Generated by Django 5.1.6 on 2025-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_tasksolutions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolutions',
            name='status',
            field=models.CharField(choices=[('WA', 'WA'), ('OK', 'OK'), ('PA', 'PA')]),
        ),
    ]
