# Generated by Django 5.1.6 on 2025-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_tasksolutions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolutions',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
