# Generated by Django 5.1.6 on 2025-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_tasksolutions_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolutions',
            name='status',
            field=models.CharField(choices=[('WA', 'WA'), ('OK', 'OK'), ('PA', 'PA'), ('NA', 'NA')]),
        ),
    ]
