# Generated by Django 5.1.6 on 2025-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_task_files_uploadfiles_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='name',
            field=models.CharField(default='file', max_length=1023),
        ),
    ]
