# Generated by Django 5.1.6 on 2025-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_uploadfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='location',
            field=models.CharField(default='http://127.0.0.1:8000/media/uploads/пик_jFMeAEB.xlsx', max_length=1023),
        ),
    ]
