# Generated by Django 5.1.6 on 2025-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_uploadfiles_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='location',
            field=models.CharField(max_length=1023),
        ),
    ]
