# Generated by Django 5.1.6 on 2025-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_uploadfiles_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
