# Generated by Django 5.1.6 on 2025-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_task_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
