# Generated by Django 5.1.6 on 2025-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_alter_task_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('table', 'table'), ('comparison', 'comparison'), ('sorting', 'sorting'), ('choice', 'choice'), ('open_answer', 'open_answer'), ('no_answer', 'no_answer')]),
        ),
    ]
