# Generated by Django 5.1.6 on 2025-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_alter_task_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumberinexam',
            name='answer_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
