# Generated by Django 5.1.6 on 2025-04-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_task_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolutions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
