# Generated by Django 5.1.6 on 2025-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_alter_tasksolutions_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuality',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
