# Generated by Django 5.1.6 on 2025-04-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_actuality_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknumberinexam',
            name='slug',
        ),
    ]
