# Generated by Django 5.1.6 on 2025-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_remove_tasknumberinexam_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTopic',
        ),
        migrations.AddField(
            model_name='tasksubject',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
